### ISSUE TITLE
impl. Array#first

### ISSUE THREAD

**Issue by yhara** [yhara/shiika#101]
Successor of #84 

- [x] #104 `[1,2]` should be inferred as `Array<Int>`
- [x] #108 Fix codegen for `[1,2]`
  - [x] ~~`Array<Int>.new` should be exist~~ we can just call `Array<T>.new` instead.
- [x] #109 Extend SkClass to have (0 or more) type parameters
- [x] #109 Support type parameter on class definition
- [x] #112 Support type parameter on method return value
- [x] #112 impl. Array#first
- [ ] `[1].first` should be inferred as Int
