### ISSUE TITLE
impl. anonymous function

### ISSUE THREAD

**Issue by yhara** [yhara/shiika#121]
Implement anonymous function (or, lambda)

Syntax:

```
fn(x){ x + 1 }

# Also,
ary.map{|x| x + 1}
# is a syntax sugar of 
ary.map(fn(x){ x + 1 })
# but maybe I'll make another issue for this
```

- [x] Add type `Fn1` #122 
- [x] Parse anon-func #123
- [x] Codegen for anon-funcs #127
- [x] Support calling anon-funcs #131 
- [ ] ~~Support capturing free-variables~~ 
- [ ] ~~Add types `Fn0<T>` .. `Fn9<S1, S2 ... S9, T>`~~

**Comment by yhara** [comment]
Closed by #131
