### ISSUE TITLE
Array literal

### ISSUE THREAD

**Issue by yhara** [yhara/shiika#84]
Long way to go...

Especially, code gen of Float/Int/Bool needs to be reconsidered to support `Array<Object>`.

- [x] #85 parser
- [x] #85 generic type
- [x] #91 change Float to llvm struct
- [x] #92 embed Int into pointer or make it llvm struct
- [x] #95 embed Bool into pointer or make it llvm struct
- [x] #97 codegen for array literal (`[Object.new]`)
- [x] #100 codegen for non-Object item (`[1,2,3]`)
  - cast is needed (Int -> Object)

**Comment by yhara** [comment]
Next: #101
